#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
from textwrap import dedent

try:
    import tomllib  # py311+
except ModuleNotFoundError:  # pragma: no cover
    tomllib = None  # type: ignore[assignment]


ROOT = Path(__file__).resolve().parents[1]
POLICY_PATH = ROOT / ".harness" / "policy.toml"
TASK_PATH = ROOT / ".harness" / "task.md"
HOOK_PATH = ROOT / ".harness" / "hooks" / "policy_hook.py"


def load_policy() -> dict:
    if tomllib is None:
        raise RuntimeError("Python 3.11+ required for tomllib")
    return tomllib.loads(POLICY_PATH.read_text(encoding="utf-8"))


def load_task() -> str:
    if not TASK_PATH.exists():
        return ""
    return TASK_PATH.read_text(encoding="utf-8").strip()


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def policy_summary(policy: dict) -> str:
    paths = policy.get("paths", {})
    commands = policy.get("commands", {})
    diff_budget = policy.get("diff_budget", {})
    enforcement = policy.get("enforcement", {})

    blocked_paths = paths.get("blocked_write_paths", paths.get("blocked_paths", []))
    blocked_cmds = commands.get("blocked_prefixes", [])
    allowed_cmds = commands.get("allowed_prefixes", [])
    scope = enforcement.get("scope", "writes_and_high_risk_only")
    unknown = enforcement.get("unknown_command", "allow_warn")
    budget_enabled = bool(diff_budget.get("enabled", False))

    return dedent(
        f"""\
        ## Policy Summary

        Enforcement scope:
        - `{scope}`
        - Unknown command handling: `{unknown}`

        Path policy:
        - Mode: `blocklist_only`
        - Blocked write paths: {", ".join(f"`{p}`" for p in blocked_paths) if blocked_paths else "(none)"}

        Command policy:
        - Blocked (destructive) prefixes: {", ".join(f"`{c}`" for c in blocked_cmds) if blocked_cmds else "(none)"}
        - Documented read-only prefixes: {", ".join(f"`{c}`" for c in allowed_cmds) if allowed_cmds else "(none)"}

        Diff budget:
        - Enabled: `{str(budget_enabled).lower()}`
        """
    ).rstrip()


def render_instruction(platform: str, task_text: str, summary: str) -> str:
    platform_note = {
        "AGENTS.md": "Codex",
        "CLAUDE.md": "Claude",
        "GEMINI.md": "Gemini",
    }[platform]
    task_block = task_text or "No task content found in `.harness/task.md`."
    return dedent(
        f"""\
        <!-- Generated by .harness/sync.py. Do not edit directly. -->

        # Harness Instructions For {platform_note}

        # Harness Task

        {task_block}

        {summary}
        """
    )


def render_codex_hooks() -> str:
    payload = {
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "Bash",
                    "hooks": [
                        {
                            "type": "command",
                            "command": f"python3 {HOOK_PATH.relative_to(ROOT)} PreToolUse",
                        }
                    ],
                }
            ],
            "PostToolUse": [
                {
                    "matcher": "Bash",
                    "hooks": [
                        {
                            "type": "command",
                            "command": f"python3 {HOOK_PATH.relative_to(ROOT)} PostToolUse",
                        }
                    ],
                }
            ],
            "Stop": [
                {
                    "matcher": "Bash",
                    "hooks": [
                        {
                            "type": "command",
                            "command": f"python3 {HOOK_PATH.relative_to(ROOT)} Stop",
                        }
                    ],
                }
            ],
        }
    }
    return json.dumps(payload, indent=2) + "\n"


def render_claude_settings() -> str:
    payload = {
        "hooks": {
            "pre_command": f"python3 {HOOK_PATH.relative_to(ROOT)} PreToolUse",
            "post_command": f"python3 {HOOK_PATH.relative_to(ROOT)} PostToolUse",
        }
    }
    return json.dumps(payload, indent=2) + "\n"


def render_gemini_settings() -> str:
    payload = {
        "hooks": {
            "pre_command": f"python3 {HOOK_PATH.relative_to(ROOT)} PreToolUse",
            "post_command": f"python3 {HOOK_PATH.relative_to(ROOT)} PostToolUse",
        }
    }
    return json.dumps(payload, indent=2) + "\n"


def main() -> int:
    policy = load_policy()
    task_text = load_task()
    summary = policy_summary(policy)

    write(ROOT / "AGENTS.md", render_instruction("AGENTS.md", task_text, summary))
    write(ROOT / "CLAUDE.md", render_instruction("CLAUDE.md", task_text, summary))
    write(ROOT / "GEMINI.md", render_instruction("GEMINI.md", task_text, summary))

    write(ROOT / ".codex" / "hooks.json", render_codex_hooks())
    write(ROOT / ".claude" / "settings.json", render_claude_settings())
    write(ROOT / ".gemini" / "settings.json", render_gemini_settings())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
