#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
from textwrap import dedent

try:
    import tomllib  # py311+
except ModuleNotFoundError:  # pragma: no cover
    tomllib = None  # type: ignore[assignment]


ROOT = Path(__file__).resolve().parents[1]
POLICY_PATH = ROOT / ".harness" / "policy.toml"
TASK_PATH = ROOT / ".harness" / "task.md"
SHARED_INSTRUCTIONS_PATH = ROOT / ".harness" / "instructions.md"
TEMPLATES_DIR = ROOT / ".harness" / "templates"
INSTRUCTION_TMPL_PATH = TEMPLATES_DIR / "instruction.md.tmpl"
COMMANDS_TMPL_PATH = TEMPLATES_DIR / "commands.md.tmpl"
POLICY_HOOK_PATH = ROOT / ".harness" / "hooks" / "policy_hook.py"
STOP_HOOK_PATH = ROOT / ".harness" / "hooks" / "stop_hook.py"


def load_policy() -> dict:
    if tomllib is None:
        raise RuntimeError("Python 3.11+ required for tomllib")
    return tomllib.loads(POLICY_PATH.read_text(encoding="utf-8"))


def load_task() -> str:
    if not TASK_PATH.exists():
        return ""
    return TASK_PATH.read_text(encoding="utf-8").strip()


def load_template(path: Path, default_text: str) -> str:
    if path.exists():
        return path.read_text(encoding="utf-8")
    return default_text


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_if_exists(path: Path, text: str) -> None:
    if path.exists():
        path.write_text(text, encoding="utf-8")


def as_markdown_list(items: list[str]) -> str:
    if not items:
        return "- (none)"
    return "\n".join(f"- `{item}`" for item in items)


def normalize_task(task_text: str) -> str:
    if not task_text:
        return "No task content found in `.harness/task.md`."

    lines = task_text.splitlines()
    if lines and lines[0].strip().lower() == "# harness task":
        lines = lines[1:]
        while lines and not lines[0].strip():
            lines = lines[1:]
    result = "\n".join(lines).strip()
    return result or "No task content found in `.harness/task.md`."


def unknown_mode_behavior(unknown_mode: str) -> str:
    if unknown_mode == "allow_warn":
        return "commands outside configured prefixes are warned and allowed"
    if unknown_mode == "allow_silent":
        return "commands outside configured prefixes are allowed silently"
    return "commands outside configured prefixes are denied"


def policy_summary(policy: dict) -> str:
    paths = policy.get("paths", {})
    commands = policy.get("commands", {})
    enforcement = policy.get("enforcement", {})

    blocked_paths = paths.get("blocked_write_paths", [])
    blocked_cmds = commands.get("blocked_prefixes", [])
    allowed_cmds = commands.get("allowed_prefixes", [])
    write_cmds = commands.get("write_prefixes", [])
    scope = enforcement.get("scope", "writes_and_high_risk_only")
    unknown = enforcement.get("unknown_command", "allow_warn")

    return dedent(
        f"""\
        ## Policy Summary

        Enforcement scope:
        - `{scope}`
        - Unknown command handling: `{unknown}` ({unknown_mode_behavior(unknown)})

        Path policy:
        - Mode: `{paths.get('mode', 'blocklist_only')}`
        - Blocked write paths: {", ".join(f"`{p}`" for p in blocked_paths) if blocked_paths else "(none)"}

        Command policy:
        - Blocked (destructive) prefixes: {", ".join(f"`{c}`" for c in blocked_cmds) if blocked_cmds else "(none)"}
        - Read-only prefixes: {", ".join(f"`{c}`" for c in allowed_cmds) if allowed_cmds else "(none)"}
        - Write prefixes: {", ".join(f"`{c}`" for c in write_cmds) if write_cmds else "(none)"}

        Hook output:
        - `allow`: no output
        - `warn`: `WARN <code>` (stderr, single line)
        - `deny`: `DENY <code>[:detail]` (stdout, single line)
        """
    ).rstrip()


def render_shared_instruction(task_text: str, summary: str) -> str:
    default_template = dedent(
        """\
        <!-- Generated by .harness/sync.py. Do not edit directly. -->

        # Harness Shared Instructions

        This file is the single source of truth for harness instructions.

        ## Harness Task

        {task_body}

        {policy_summary}
        """
    )
    template = load_template(INSTRUCTION_TMPL_PATH, default_template)
    return template.format(
        task_body=normalize_task(task_text),
        policy_summary=summary,
    ).rstrip() + "\n"


def render_agent_pointer(platform: str) -> str:
    return dedent(
        f"""\
        <!-- Generated by .harness/sync.py. Do not edit directly. -->

        # {platform} Instructions

        See [shared instructions](.harness/instructions.md)
        """
    ).rstrip() + "\n"


def render_commands_rules(policy: dict) -> str:
    commands = policy.get("commands", {})
    enforcement = policy.get("enforcement", {})
    allowed = list(commands.get("allowed_prefixes", []))
    write = list(commands.get("write_prefixes", []))
    blocked = list(commands.get("blocked_prefixes", []))
    unknown = enforcement.get("unknown_command", "allow_warn")

    default_template = dedent(
        """\
        <!-- Generated by .harness/sync.py. Do not edit directly. -->

        # Codex Command Rules

        Readable copy of the shared shell-command policy used by the Harness hook.

        ## Matching Rules

        - Commands are split by `&&`, `||`, `;`, and `|`, then evaluated segment-by-segment.
        - The strictest matched decision wins (`deny` > `warn` > `allow`).
        - Blocked prefixes always deny.
        - Commands outside configured prefixes are handled by `unknown_command = {unknown_mode}`.

        ## Hook Output

        - `allow`: no output
        - `warn`: `WARN <code>` (stderr)
        - `deny`: `DENY <code>[:detail]` (stdout)

        ## Read Command Prefixes

        {read_commands}

        ## Write Command Prefixes

        {write_commands}

        ## Blocked Command Prefixes

        {blocked_commands}
        """
    )
    template = load_template(COMMANDS_TMPL_PATH, default_template)
    return template.format(
        unknown_mode=unknown,
        read_commands=as_markdown_list(allowed),
        write_commands=as_markdown_list(write),
        blocked_commands=as_markdown_list(blocked),
    ).rstrip() + "\n"


def render_codex_hooks() -> str:
    hook = POLICY_HOOK_PATH.relative_to(ROOT)
    stop_hook = STOP_HOOK_PATH.relative_to(ROOT)
    payload = {
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "Bash",
                    "hooks": [
                        {
                            "type": "command",
                            "command": f"python3 {hook} PreToolUse codex",
                        }
                    ],
                }
            ],
            "PostToolUse": [
                {
                    "matcher": "Bash",
                    "hooks": [
                        {
                            "type": "command",
                            "command": f"python3 {hook} PostToolUse codex",
                        }
                    ],
                }
            ],
            "Stop": [
                {
                    "matcher": "Bash",
                    "hooks": [
                        {
                            "type": "command",
                            "command": f"python3 {stop_hook} Stop codex",
                        }
                    ],
                }
            ],
        }
    }
    return json.dumps(payload, indent=2) + "\n"


def render_platform_settings(platform: str) -> str:
    hook = POLICY_HOOK_PATH.relative_to(ROOT)
    payload = {
        "hooks": {
            "pre_command": f"python3 {hook} PreToolUse {platform}",
            "post_command": f"python3 {hook} PostToolUse {platform}",
        }
    }
    return json.dumps(payload, indent=2) + "\n"


def main() -> int:
    policy = load_policy()
    task_text = load_task()
    summary = policy_summary(policy)

    write(SHARED_INSTRUCTIONS_PATH, render_shared_instruction(task_text, summary))
    write_if_exists(ROOT / "AGENTS.md", render_agent_pointer("Codex"))
    write_if_exists(ROOT / "CLAUDE.md", render_agent_pointer("Claude"))
    write_if_exists(ROOT / "GEMINI.md", render_agent_pointer("Gemini"))

    write(ROOT / ".codex" / "hooks.json", render_codex_hooks())
    write(ROOT / ".codex" / "rules" / "commands.md", render_commands_rules(policy))
    write(ROOT / ".claude" / "settings.json", render_platform_settings("claude"))
    write(ROOT / ".gemini" / "settings.json", render_platform_settings("gemini"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
